{
  lib,
  inputs,
  pkgs,
  ...
}:

# ---------------------------------------------------------------------------
# WARNING: The Bluetooth A2DP workaround below was generated by an AI
# assistant (OpenCode). It implements a well-known community workaround, but
# you should review it before relying on it in production.
#
# What is happening:
#   Apple Silicon Macs use Broadcom Bluetooth controllers (BCM4377/BCM4378/...).
#   These chips need the vendor-specific HCI_BRCM_SET_ACL_PRIORITY command
#   (OGF 0x3f, OCF 0x57) to mark an A2DP ACL link as high-priority. BlueZ does
#   not send this command automatically, so audio stutters or drops out for
#   ~10 seconds whenever the link is contended (e.g. during a scan).
#
# What Fedora Asahi Remix does:
#   Fedora Asahi Remix does not currently ship a BlueZ-level fix. Users apply
#   the same userspace workaround that is implemented below:
#     https://github.com/christian-korneck/asahi-bt-a2dp-fix
#   A proper kernel-level fix is being worked on by the Asahi Linux project:
#     https://github.com/bluez/bluez/issues/722
#     https://ratatoskr.run/asahi/2026/05/17026823
#   Once that patch lands in the Asahi kernel used by this config, the
#   asahi-bt-a2dp-fix service can be removed.
# ---------------------------------------------------------------------------

let
  # AI-GENERATED WORKAROUND START
  # Workaround for stuttering A2DP audio on Apple Silicon Broadcom Bluetooth
  # controllers (BCM4377/BCM4378/...). BlueZ does not send the vendor-specific
  # HCI_BRCM_SET_ACL_PRIORITY command that these chips need for stable ACL
  # audio links, so we send it ourselves whenever an A2DP headset connects.
  # See: https://github.com/bluez/bluez/issues/722
  asahi-bt-a2dp-fix = pkgs.writeShellScriptBin "asahi-bt-a2dp-fix" ''
    ${pkgs.expect}/bin/unbuffer ${pkgs.bluez}/bin/bluetoothctl --monitor | while read -r line; do
      if [[ "$line" =~ Device.*([0-9A-F:]{17}).*Connected:\ yes ]]; then
        mac="''${BASH_REMATCH[1]}"
        sleep 2
        ${pkgs.bluez}/bin/bluetoothctl info "$mac" | grep -q "Audio Sink" || continue
        handle=$(${pkgs.bluez}/bin/hcitool con | grep -i "$mac" | grep -oP 'handle \K[0-9]+')
        if [[ -n "$handle" ]]; then
          ${pkgs.bluez}/bin/hcitool cmd 0x3f 0x57 "$(printf 0x%02X "$handle")" 0x00 0x01
        fi
      fi
    done
  '';
  # AI-GENERATED WORKAROUND END
in
{
  imports = [
    inputs.nixos-apple-silicon.nixosModules.apple-silicon-support
  ];
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  hardware.bluetooth.enable = true;

  networking.networkmanager.wifi.backend = "iwd";
  hardware.asahi.enable = true;
  boot.kernelPackages =
    lib.mkForce
      inputs.nixos-apple-silicon.packages."aarch64-linux".installer-bootstrap.config.boot.kernelPackages;
  hardware.asahi.peripheralFirmwareDirectory = inputs.macbook-m1-alper-firmware;
  boot.extraModprobeConfig = ''
    options hid_apple swap_opt_cmd=1
    options hid_apple swap_fn_leftctrl=1
  '';
  hardware.apple.touchBar = {
    enable = true;
    package = pkgs.tiny-dfr;
  };

  # AI-GENERATED WORKAROUND START
  # Apply the Broadcom ACL-priority workaround automatically on A2DP connects.
  systemd.services.asahi-bt-a2dp-fix = {
    description = "Bluetooth A2DP stutter fix for Apple Silicon";
    after = [ "bluetooth.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${asahi-bt-a2dp-fix}/bin/asahi-bt-a2dp-fix";
      Restart = "always";
      RestartSec = 5;
    };
  };
  # AI-GENERATED WORKAROUND END

  # AI-GENERATED WORKAROUND START
  # Increase the internal latency offset for Bluetooth outputs so PipeWire does
  # not under-run on the somewhat higher-latency Asahi Bluetooth link.
  services.pipewire.wireplumber.extraConfig."50-bt-latency" = {
    "monitor.bluez.rules" = [
      {
        matches = [
          { "node.name" = "~bluez_output.*"; }
        ];
        actions = {
          update-props = {
            "latency.internal.ns" = 100000000;
          };
        };
      }
    ];
  };
  # AI-GENERATED WORKAROUND END

  swapDevices = [
    {
      priority = 0;
      device = "/.swap-files/swap-file";
      size = 32 * 1024;
      encrypted = {
        enable = true;
        label = "cryptroot";
        blkDev = "/dev/disk/by-label/main-luks";
      };
    }
  ];

}
