#/* vim: set filetype=hyprlang : */
################
### MONITORS ###
################
$scale_mul = 1;
# See https://wiki.hypr.land/Configuring/Monitors/
monitor=desc:BOE NE173QHM-NZ2,2560x1440@240.00Hz,auto-left,{{1.25 * $scale_mul}}
monitor=desc:Samsung Electric Company SyncMaster HMDSB05010,1440x900@75Hz ,auto-right,{{0.83 * $scale_mul}}
monitor=,preferred,auto,auto

