# GENERATED BY AI at first

# === D-Bus (session + system) ===
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
dbus-system none

# === Basic sandboxing ===
caps.drop all
noroot
nogroups
nonewprivs
seccomp
ipc-namespace
machine-id
private-tmp
private-dev

# === Hardware / subsystem isolation ===
nosound
no3d
nodvd
notv
nou2f
novideo
noinput

private-cache
private-dev
private-tmp

blacklist ${HOME}/.*
tmpfs ~/.config
tmpfs ~/.config
# whitelist ${HOME}/Projects
# whitelist ${HOME}/MyConfig
whitelist  ${HOME}/.config/opencode
whitelist  ${HOME}/.omp


# === Runtime agents and system secret directories ===
blacklist ${RUNUSER}
blacklist ${RUNUSER}/ssh-agent
blacklist ${RUNUSER}/gnupg
blacklist ${RUNUSER}/app
blacklist ${RUNUSER}/keyring
blacklist ${RUNUSER}/bus
blacklist /run/secrets
blacklist /run/secrets.d

