# GENERATED BY AI at first

# === D-Bus (session + system) ===
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
dbus-system none

# === Basic sandboxing ===
caps.drop all
noroot
nogroups
nonewprivs
seccomp
ipc-namespace
machine-id
private-tmp
private-dev

# === Hardware / subsystem isolation ===
nosound
no3d
nodvd
notv
nou2f
novideo
noinput

tmpfs ${HOME}
whitelist ${HOME}/Projects
whitelist ${HOME}/MyConfig


# === Runtime agents and system secret directories ===
tmpfs ${RUNUSER}
blacklist ${RUNUSER}/ssh-agent
blacklist ${RUNUSER}/gnupg
blacklist ${RUNUSER}/app
blacklist ${RUNUSER}/keyring
blacklist ${RUNUSER}/bus
blacklist /run/secrets
blacklist /run/secrets.d

