# GENERATED BY AI at first

# === D-Bus (session + system) ===
dbus-user filter
dbus-user.talk org.freedesktop.Notifications
dbus-system none

# === Basic sandboxing ===
caps.drop all
nogroups
nonewprivs
seccomp
ipc-namespace
machine-id
private-tmp
private-dev
# protocol inet,inet6

# === Hardware / subsystem isolation ===
nosound
no3d
nodvd
notv
nou2f
novideo
noinput

whitelist  ${HOME}/.nuget
whitelist  ${HOME}/.cache/opencode
whitelist  ${HOME}/.cache/codebase-memory-mcp
whitelist  ${HOME}/.config/opencode
whitelist  ${HOME}/.local/share/opencode
whitelist  ${HOME}/.local/state/opencode
whitelist  ${HOME}/.local/share/direnv/allow
whitelist  ${HOME}/.omp

# === Runtime agents and system secret directories ===
blacklist ${RUNUSER}
blacklist ${RUNUSER}/ssh-agent
blacklist ${RUNUSER}/gnupg
blacklist ${RUNUSER}/app
blacklist ${RUNUSER}/keyring
blacklist ${RUNUSER}/bus
blacklist /run/secrets
blacklist /run/secrets.d

